asg/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

cal/urls.py
from django.conf.urls import patterns, url
from cal.views import EventListView, EventDetailView, EntryCreateView,\
        EntryDeleteView, EventArchiveView, EventDetailPDFView


urlpatterns = patterns('',
                       url(r'^$', EventListView.as_view(), name='event-index'),
                       url(r'^events/$', EventListView.as_view(), name='event-list'),
                       url(r'^events/archive/$', EventArchiveView.as_view(), name='event-archive'),
                       url(r'^events/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event-detail'),
                       url(r'^events/(?P<pk>\d+)/pdf/$', EventDetailPDFView.as_view(), name='event-pdf-detail'),
                       url(r'^events/(?P<pk>\d+)/signup/s(?P<slot_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create-slot'),
                       url(r'^events/(?P<pk>\d+)/signup/f(?P<faction_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create'),
                       url(r'^events/signout/(?P<pk>\d+)/$',
                           EntryDeleteView.as_view(), name='entry-delete'),
                       )

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework import routers
from cal import views
from asg.users import views as uviews
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)
router.register(r'pgroups', views.PGroupViewSet)
router.register(r'factions', views.FactionViewSet)
router.register(r'slots', views.SlotViewSet)
router.register(r'entries', views.EntryViewSet)
router.register(r'users', uviews.UserViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("asg.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^api/', include(router.urls)),
    url(r'^', include('cal.urls', namespace='cal')),
    url(r'^nested_admin/', include('nested_admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

urlpatterns += [
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^pages/', include(wagtail_urls)),
]

asg/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message=(
                                 "Numer telefonu musi zostać wpisany w formacie: '+999999999'."))
    phone_number = models.CharField(validators=[phone_regex], max_length=255,
                                    blank=True, verbose_name='numer telefonu')  # validators should be a list

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    date_of_birth = models.DateField(_("Data urodzenia"), blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

User._meta.get_field('first_name').verbose_name = 'imię'
User._meta.get_field('last_name').verbose_name = 'nazwisko'

cal/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from location_field.models.plain import PlainLocationField
from django_extensions.db.models import TimeStampedModel
from django.core.exceptions import ValidationError


def validate_slot_number(value):
    try:
        faction = Faction.objects.get(id=value)
        if faction.event.slot_limit_reached():
            raise ValidationError(
                    'Przekroczono limit miejsc',
                    )
    except:
        pass


class Event(TimeStampedModel):
    title = models.CharField(max_length=255, verbose_name='tytuł')
    description = models.TextField(verbose_name='opis', blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                              blank=True, verbose_name='stworzone przez')
    poster = models.ImageField(upload_to='posters', blank=True, null=True,
                               verbose_name='zdjecie')
    datetime = models.DateTimeField(default=timezone.now,
                                    verbose_name='data i czas')
    starttime1 = models.TimeField(verbose_name='rozgrywki1')
    starttime2 = models.TimeField(verbose_name='rozgrywki2')
    endtime1 = models.TimeField(verbose_name='koniec1')
    endtime2 = models.TimeField(verbose_name='koniec2')
    location = PlainLocationField(zoom=14, default='53.43,14.56')
    location_video = models.URLField(verbose_name='miejsce zbiorki (video)',
                                     blank=True, null=True)
    areamap = models.FileField(verbose_name='mapa', null=True, blank=True)
    fps = models.TextField(verbose_name='fps', blank=True)
    ammo = models.TextField(verbose_name='amunicja', blank=True)
    terms = models.TextField(verbose_name='regulamin', blank=True)
    entry_fee = models.TextField(verbose_name='wpisowe', blank=True)
    slot_limit = models.PositiveIntegerField(
        verbose_name='limit miejsc', blank=True, null=True, default=None)
    pyro = models.BooleanField(verbose_name='pirotechnika', default=False)
    underage = models.BooleanField(verbose_name='nieletni', default=False)
    rules = models.TextField(verbose_name='zasady gry', blank=True)
    info = models.TextField(verbose_name='wiecej informacji',
                            blank=True)
    link = models.URLField(blank=True)
    is_open = models.BooleanField(default=True, verbose_name='otwarte')

    rule_fields_names = ['fps', 'ammo', 'terms', 'entry_fee', 'rules', 'info']

    class Meta:
        verbose_name = 'wydarzenie'
        verbose_name_plural = 'wydarzenia'

    def __str__(self):
        return self.title

    @property
    def signed_up_users(self):
        users = []
        for faction in self.factions.all():
            users.extend(faction.users.all())
        return users

    def slot_limit_reached(self):
        try:
            slot_limit_exceeded = len(self.signed_up_users) >= self.slot_limit
            if slot_limit_exceeded:
                return True
            return False
        except TypeError:
            return False

    def user_can_sign_up(self, user):
        if user.is_anonymous() or self.slot_limit_reached() or not self.is_open or \
                user in self.signed_up_users:
            return False
        return True

    # generator iterujacy po liscie nazw pol i zwracajacy pare: nazwa pola, wartosc pola
    def get_rule_fields(self):
        for field_name in self.rule_fields_names:
            yield self._meta.get_field(field_name).verbose_name, getattr(self, field_name)

    # properties potrzebne do wyświetlania mapy z lokalizacją
    @property
    def location_lat(self):
        return self.location.split(',')[0].strip()

    @property
    def location_lng(self):
        return self.location.split(',')[1].strip()


class PGroup(TimeStampedModel):
    name = models.CharField(max_length=255, verbose_name='nazwa')
    logo = models.ImageField(upload_to='logos', blank=True, null=True)
    website = models.URLField(null=True, blank=True, verbose_name='strona www')
    description = models.TextField(null=True, blank=True, verbose_name='opis')

    class Meta:
        verbose_name = 'grupa'
        verbose_name_plural = 'grupy'

    def __str__(self):
        return self.name


class Faction(TimeStampedModel):
    event = models.ForeignKey(Event, related_name='factions')
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='cal.Entry',
                                   related_name='factions', verbose_name='użytkownicy')

    class Meta:
        verbose_name = 'frakcja'
        verbose_name_plural = 'frakcje'

    def __str__(self):
        return '{0} - {1}'.format(self.event, self.name)

    def get_non_slot_players(self):
        return self.entries.filter(slot=None)


class Slot(TimeStampedModel):
    name = models.CharField(max_length=200, verbose_name='nazwa',
                            blank=False, null=False)
    faction = models.ForeignKey(Faction)

    class Meta:
        verbose_name = "slot"
        verbose_name_plural = 'sloty'

    def __str__(self):
        return '{0} - {1} | {2}'.format(self.name, self.faction.event, self.faction)


class Entry(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='entries',
                             verbose_name='użytkownik')
    slot = models.OneToOneField(Slot, blank=True, null=True)
    faction = models.ForeignKey(Faction, related_name='entries', blank=False, null=False,
                                validators=[validate_slot_number])

    class Meta:
        verbose_name = 'zapis'
        verbose_name_plural = 'zapisy'
        ordering = ['pk']

    def __str__(self):
        return "{0} - {1} | {2}".format(self.user, self.slot, self.faction)

cal/forms.py
from django import forms
from cal.models import Entry


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['user']

asg/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User
from django.forms.models import modelform_factory
from django.forms.widgets import DateInput

from rest_framework import viewsets, mixins
from .serializers import UserSerializer
# from .permissions import IsUser
# from rest_framework.permissions import IsAdminUser, IsAuthenticated


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    # fields = ['first_name', 'last_name', 'phone_number', 'date_of_birth', ]

    # we already imported User in the view code above, remember?
    model = User
    form_class = modelform_factory(User,
                                   widgets={'date_of_birth': DateInput},
                                   fields=['first_name', 'last_name', 'phone_number', 'date_of_birth'])

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


# class UserViewSet(viewsets.ModelViewSet):
class UserViewSet(mixins.RetrieveModelMixin,
                  mixins.ListModelMixin,
                  viewsets.GenericViewSet):
    """
    API endpoint for users
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer

    # def update(self, request, *args, **kwargs):
    #     self.methods = ('put', )
    #     self.permission_classes = (IsUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

    # def create(self, request, *args, **kwargs):
    #     self.methods = ('post', )
    #     self.permission_classes = (IsAdminUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

asg/templates/cal/entry_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Wypisz się" />
</form>
{% endblock %}

asg/templates/cal/entry_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="{{ action_name }}" />
</form>
{% endblock %}

asg/templates/cal/event_detail.html
{% extends 'base.html' %}
{% load cal_tags %}
{% load l10n %}

{% block title %}
    {{ event.title}}
{% endblock %}

{% block css %}
    {{block.super}}
    <style>
      #map {
        height: 400px;
        width: 500px;
      }
    </style>
{% endblock %}

{% block angular %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {# jquery ui accordion #}
    <div class="card">
        <div class="card-header">
            <h1>{{ event.title }}
            {% if request.user.is_staff %}
                <span class="pull-md-right">
                    <a href="{% url 'cal:event-pdf-detail' event.pk %}" class="btn btn-primary">PDF</a>
                </span>
            {% endif %}
            </h1>
        </div>
        <ul id="accordion" role="tablist" class="list-group list-group-flush">
            <li class="list-group-item">
                <a role="tab" data-toggle="collapse" data-parent="#accordion" href="#descriptionCollapse" data-target="#descriptionCollapse">
                    <h4 class="list-group-item-heading">Opis</h4>
                </a>
                <p role="tabpanel" id="descriptionCollapse" class="list-group-item-text collapse in">
                    {{ event.description }}
                </p>
            </li>
            <li class="list-group-item">
                <a role="tab" data-toggle="collapse" data-parent="#accordion" href="#datetimeCollapse" class="collapsed" data-target="#datetimeCollapse">
                    <h4 class="list-group-item-heading">Data i Czas</h4>
                </a>
                <div role="tabpanel" id="datetimeCollapse" class="list-group-item-text collapse">
                    <p>Zbiórka: {{ event.datetime|localize }}</p>
                    <p>Początek rozgrywki: {{ event.starttime1|localize }} - {{ event.starttime2|localize }}</p>
                    <p>Zakończenie rozgrywki: {{ event.endtime1|localize }} - {{ event.endtime2|localize }}</p>
                </div>
            </li>
            <li class="list-group-item">
                <a role="tab" data-toggle="collapse" data-parent="#accordion" href="#locationCollapse" class="collapsed" data-target="#locationCollapse"
                    onclick="google.maps.event.trigger(map, 'resize');">
                    <h4 class="list-group-item-heading">Lokalizacja</h4>
                </a>
                <div role="tabpanel" id="locationCollapse" class="list-group-item-text collapse">
                    <p><a href="{{ event.location_video }}">Wideo z intrukcją dojazdu</a></p>
                    <div id="map"></div>
                </div>
            </li>
            <li class="list-group-item">
                <a role="tab" data-toggle="collapse" data-parent="#accordion" href="#rulesCollapse" class="collapsed" data-target="#rulesCollapse">
                    <h4 class="list-group-item-heading">Zasady</h4>
                </a>
                <div role="tabpanel" id="rulesCollapse" class="list-group-item-text collapse">
                    {% for field, value in event.get_rule_fields %}
                        {% if value %}
                            <h5>{{ field|title }}:</h5>
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>


    <div class="card-columns">
        {% for faction in event.factions.all %}
            <div class="card">
                <div class="card-header">
                    <span>{{ faction.name | upper }}</span>
                    <span class="pull-md-right">
                    {% if user_can_signup %}
                        <a href="{% url 'cal:entry-create' event.pk faction.pk %}"
                           class="btn btn-primary btn-sm" id="{{faction.name}}">+</a>
                    {% endif %}
                    </span>
                </div>
                <ul class="list-group list-group-flush">
                    {% for slot in faction.slot_set.all %}
                        <li class="list-group-item">
                            {{ slot.name }}:
                            <span class="pull-xs-right">
                                {% if slot.entry.user %}
                                    {{ slot.entry.user }}
                                    {% compare_users slot.entry.user request.user as is_request_user %}
                                    {% if is_request_user %}
                                        <a href="{% url 'cal:entry-delete' slot.entry.pk %}">
                                            [-]
                                        </a>
                                    {% endif %}
                                {% elif user_can_signup %}
                                <a href="{% url 'cal:entry-create-slot' event.pk slot.pk %}">
                                    ZAPISZ SIĘ
                                </a>
                                {% endif %}
                            </span>
                        </li>
                    {% endfor %}
                    {% for entry in faction.get_non_slot_players %}
                        <li class="list-group-item">
                            <span>-</span>
                            <span class="pull-xs-right">{{ entry.user }}
                                {% compare_users entry.user request.user as is_request_user %}
                                {% if is_request_user %}
                                    <a href="{% url 'cal:entry-delete' entry.pk %}">
                                        [-]
                                    </a>
                                {% endif %}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block javascript %}
    {{ block.super }} 
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_JSx4ef6EfhXIBTrfK4XVVrVVqUsNVf4&callback=initMap">
        </script>
        <script>
            $('#locationCollapse').on('shown.bs.collapse', function initMap() {
                var center = new google.maps.LatLng({{ event.location }});

                var map = new google.maps.Map(document.getElementById('map'), {
                  center: center,
                  zoom: 10
                });

                var marker_pos = {lat: {{ event.location_lat }}, lng: {{ event.location_lng }} };
                var marker = new google.maps.Marker({
                  position: center,
                  map: map,
                  title: 'Miejsce zbiórki'
                });
            });
        </script>
{% endblock %}

asg/templates/cal/event_list.html
{% extends 'base.html' %}
{% block title %}Lista wydarzeń{% endblock %}
{% block content %}
<h1>Wydarzenia:</h1>
<div class="card-columns">
{% for event in events %}
    <a class="no-style" href="{% url 'cal:event-detail' event.pk %}">
        <div class="card">
            {% if event.poster %}
                <img class="card-img-top img-fluid center-block" src="{{ event.poster.url }}" alt="Card image cap">
            {% endif %}
          <div class="card-block">
          <h4 class="card-title">{{ event.title }}</h4>
          <p class="card-text">{{ event.description|truncatechars:300 }}</p>
          </div>
        </div>
    </a>
{% empty %}
    <h1>Brak wydarzeń spełniających kryteria</h1>
{% endfor %}
</div>

{% include '_pagination.html' %}
{% endblock %}

asg/templates/cal/event_list_pdf.html
<html>
 <head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <style>
      table, tr, td, th  {
    border-collapse: collapse;
        border: 1px solid #000;
      }
      table {
        width: 100%;
      }
      body {
        font-size: 14px;
      }
    </style>
 </head>
 <body>
    <h1>{{ event|title }}</h1>
    <div>{{ event.datetime.date }}
    <h2>Lista uczestników</h2>
    {% for faction in event.factions.all %}
        <h3>{{ faction.name }}</h3>
        <table style="border-width: 1px">
            <thead>
                <tr>
                    <th style="width:2em;">Lp.</th>
                    <th>Imię i nazwisko</th>
                    <th>Nick</th>
                    <th>Nr telefonu</th>
                    <th>Podpis</th>
                </tr>
            </thead>
            <tbody>
                {% for user in faction.users.all %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            {{ user.first_name }} {{ user.last_name }}
                        </td>
                        <td>
                            {{ user.username }}
                        </td>
                        <td>
                            {{ user.phone_number }}
                        </td>
                        <td>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}

 </body>
</html>