asg/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

cal/urls.py
from django.conf.urls import patterns, url
from cal.views import EventListView, EventDetailView, EntryCreateView,\
        EntryDeleteView, EventArchiveView, EventDetailPDFView


urlpatterns = patterns('',
                       url(r'^$', EventListView.as_view(), name='event-index'),
                       url(r'^events/$', EventListView.as_view(), name='event-list'),
                       url(r'^events/archive/$', EventArchiveView.as_view(), name='event-archive'),
                       url(r'^events/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event-detail'),
                       url(r'^events/(?P<pk>\d+)/pdf/$', EventDetailPDFView.as_view(), name='event-pdf-detail'),
                       url(r'^events/(?P<pk>\d+)/signup/s(?P<slot_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create-slot'),
                       url(r'^events/(?P<pk>\d+)/signup/f(?P<faction_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create'),
                       url(r'^events/signout/(?P<pk>\d+)/$',
                           EntryDeleteView.as_view(), name='entry-delete'),
                       )

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework import routers
from cal import views
from asg.users import views as uviews
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)
router.register(r'pgroups', views.PGroupViewSet)
router.register(r'factions', views.FactionViewSet)
router.register(r'slots', views.SlotViewSet)
router.register(r'entries', views.EntryViewSet)
router.register(r'users', uviews.UserViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("asg.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^api/', include(router.urls)),
    url(r'^', include('cal.urls', namespace='cal')),
    url(r'^nested_admin/', include('nested_admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

urlpatterns += [
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^pages/', include(wagtail_urls)),
]

asg/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message=(
                                 "Numer telefonu musi zostać wpisany w formacie: '+999999999'."))
    phone_number = models.CharField(validators=[phone_regex], max_length=255,
                                    blank=True, verbose_name='numer telefonu')  # validators should be a list

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    date_of_birth = models.DateField(_("Data urodzenia"), blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

User._meta.get_field('first_name').verbose_name = 'imię'
User._meta.get_field('last_name').verbose_name = 'nazwisko'

asg/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User
from django.forms.models import modelform_factory
from django.forms.widgets import DateInput

from rest_framework import viewsets, mixins
from .serializers import UserSerializer
# from .permissions import IsUser
# from rest_framework.permissions import IsAdminUser, IsAuthenticated


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    # fields = ['first_name', 'last_name', 'phone_number', 'date_of_birth', ]

    # we already imported User in the view code above, remember?
    model = User
    form_class = modelform_factory(User,
                                   widgets={'date_of_birth': DateInput},
                                   fields=['first_name', 'last_name', 'phone_number', 'date_of_birth'])

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


# class UserViewSet(viewsets.ModelViewSet):
class UserViewSet(mixins.RetrieveModelMixin,
                  mixins.ListModelMixin,
                  viewsets.GenericViewSet):
    """
    API endpoint for users
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer

    # def update(self, request, *args, **kwargs):
    #     self.methods = ('put', )
    #     self.permission_classes = (IsUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

    # def create(self, request, *args, **kwargs):
    #     self.methods = ('post', )
    #     self.permission_classes = (IsAdminUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

asg/templates/_pagination.html
<nav>
  <ul class="pagination pagination-sm">
    
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?{{ page_obj.previous_page_number.querystring }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <!-- <span class="current page">{{ page }}</span> -->
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page }}<span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <!-- <a href="?{{ page.querystring }}" class="page">{{ page }}</a> -->
                <li class="page-item"><a class="page-link" href="?{{ page.querystring }}">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?{{ page_obj.next_page_number.querystring }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

asg/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app="myApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}asg{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
{#    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.2/angular.min.js"></script>#}
    {% endblock %}

  </head>

  <body>

    {% include 'navbar.html' %}
    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      <div class="content-wrapper">
          {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
      </div>
      <div ui-view></div>

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://raw.githubusercontent.com/HubSpot/tether/master/dist/js/tether.min.js"></script>
      <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
{#      <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.2/angular-route.min.js"></script>#}
{#      <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>#}
{#      <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.2/angular-resource.min.js"></script>#}
{#      <script src="{% static 'js/app.js' %}"></script>#}
{#      <script src="{% static 'js/services.js' %}"></script>#}
{#      <script src="{% static 'js/controllers.js' %}"></script>#}
    {% endblock javascript %}
  </body>
</html>

asg/templates/navbar.html
{% load staticfiles i18n %}
<div class="m-b-lg">
  <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
    <div class="container">
      <a class="navbar-brand" href="/">asg</a>
      <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        &#9776;
      </button>
      
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'cal:event-list' %}">Wydarzenia</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'cal:event-archive' %}">Archiwum</a></li>
        </ul>
    
        <ul class="nav navbar-nav pull-xs-right">
          {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'users:detail' request.user.username  %}">Mój profil</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Wyloguj</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Rejestracja</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Logowanie</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>