asg/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

cal/urls.py
from django.conf.urls import patterns, url
from cal.views import EventListView, EventDetailView, EntryCreateView,\
        EntryDeleteView, EventArchiveView, EventDetailPDFView


urlpatterns = patterns('',
                       url(r'^$', EventListView.as_view(), name='event-index'),
                       url(r'^events/$', EventListView.as_view(), name='event-list'),
                       url(r'^events/archive/$', EventArchiveView.as_view(), name='event-archive'),
                       url(r'^events/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event-detail'),
                       url(r'^events/(?P<pk>\d+)/pdf/$', EventDetailPDFView.as_view(), name='event-pdf-detail'),
                       url(r'^events/(?P<pk>\d+)/signup/s(?P<slot_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create-slot'),
                       url(r'^events/(?P<pk>\d+)/signup/f(?P<faction_id>\d+)/$',
                           EntryCreateView.as_view(), name='entry-create'),
                       url(r'^events/signout/(?P<pk>\d+)/$',
                           EntryDeleteView.as_view(), name='entry-delete'),
                       )

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework import routers
from cal import views
from asg.users import views as uviews
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)
router.register(r'pgroups', views.PGroupViewSet)
router.register(r'factions', views.FactionViewSet)
router.register(r'slots', views.SlotViewSet)
router.register(r'entries', views.EntryViewSet)
router.register(r'users', uviews.UserViewSet)


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("asg.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^api/', include(router.urls)),
    url(r'^', include('cal.urls', namespace='cal')),
    url(r'^nested_admin/', include('nested_admin.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

urlpatterns += [
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^pages/', include(wagtail_urls)),
]

asg/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message=(
                                 "Numer telefonu musi zostać wpisany w formacie: '+999999999'."))
    phone_number = models.CharField(validators=[phone_regex], max_length=255,
                                    blank=True, verbose_name='numer telefonu')  # validators should be a list

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    date_of_birth = models.DateField(_("Data urodzenia"), blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

User._meta.get_field('first_name').verbose_name = 'imię'
User._meta.get_field('last_name').verbose_name = 'nazwisko'

asg/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User
from django.forms.models import modelform_factory
from django.forms.widgets import DateInput

from rest_framework import viewsets, mixins
from .serializers import UserSerializer
# from .permissions import IsUser
# from rest_framework.permissions import IsAdminUser, IsAuthenticated


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    # fields = ['first_name', 'last_name', 'phone_number', 'date_of_birth', ]

    # we already imported User in the view code above, remember?
    model = User
    form_class = modelform_factory(User,
                                   widgets={'date_of_birth': DateInput},
                                   fields=['first_name', 'last_name', 'phone_number', 'date_of_birth'])

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


# class UserViewSet(viewsets.ModelViewSet):
class UserViewSet(mixins.RetrieveModelMixin,
                  mixins.ListModelMixin,
                  viewsets.GenericViewSet):
    """
    API endpoint for users
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer

    # def update(self, request, *args, **kwargs):
    #     self.methods = ('put', )
    #     self.permission_classes = (IsUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

    # def create(self, request, *args, **kwargs):
    #     self.methods = ('post', )
    #     self.permission_classes = (IsAdminUser, )
    #     return super(self.__class__, self).update(request, *args, **kwargs)

asg/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">Zmień dane</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

asg/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block javascript %}
    {{ block.super }}

    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
    $(function() {
        $( "#id_date_of_birth" ).datepicker({
            changeMonth: true,
            changeYear: true
        });
    });
    </script>

{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Zmień dane</button>
          </div>
        </div>
    </form>
{% endblock %}

asg/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

{% endblock content %}